User Can View Daily Planner
htjahyon/week-planner pull request #1
Opened 2020-10-16 06:14 UTC by htjahyon

![image](https://user-images.githubusercontent.com/68126492/96219568-f1412e80-0f3b-11eb-9805-72256796119d.png)

2020-10-16 17:35 UTC, uzair-ashraf requested changes

2020-10-16 17:35 UTC, uzair-ashraf commented on index.html
> +    </section>
a section element should be used to separate your page into sections, it doesnt really make sense to do it here

You want to use a div or a button for your add entry button

2020-10-16 17:35 UTC, uzair-ashraf commented on main.js
> +}
You will not need to dynamically create your week in this application.

2020-10-16 17:35 UTC, uzair-ashraf commented on main.js
> +}
You only need to create the rows dynamically for its content, the headings will never change.

You will also need thead and tbody elements to be semantically correct.

2020-10-16 17:35 UTC, uzair-ashraf commented on main.js
> +document.querySelector(".tables").appendChild(returnTable("Description"));
If you're going to do things in the global scope to start your application you should start it with a `start` function or an `init` function

2020-10-16 17:35 UTC, uzair-ashraf commented on style.css
> +#Description {
No capitalized ids, use camelCase or kebab-case

2020-10-16 17:35 UTC, uzair-ashraf commented on style.css
> +  width:10%;
10% doesn't work if the parent element does not have a width

2020-10-17 06:47 UTC, htjahyon commented
![image](https://user-images.githubusercontent.com/68126492/96330425-e0f78500-1009-11eb-9beb-44596f35ee50.png)

2020-10-17 17:05 UTC, uzair-ashraf approved these changes

2020-10-17 17:19 UTC, merged